//Clock Input Pin
#define CLOCK_INPUT 0
//Data Memory Inputs
#define DATA_MEMORY_INPUT_ADDRESS_0 1
#define DATA_MEMORY_INPUT_ADDRESS_1 2
#define DATA_MEMORY_INPUT_ADDRESS_2 3
#define DATA_MEMORY_INPUT_ADDRESS_3 4
#define DATA_MEMORY_INPUT_ADDRESS_4 5
#define DATA_MEMORY_INPUT_ADDRESS_5 6
#define DATA_MEMORY_INPUT_ADDRESS_6 7
#define DATA_MEMORY_INPUT_ADDRESS_7 8
#define DATA_MEMORY_INPUT_WRITE_DATA_0 9
#define DATA_MEMORY_INPUT_WRITE_DATA_1 10
#define DATA_MEMORY_INPUT_WRITE_DATA_2 11
#define DATA_MEMORY_INPUT_WRITE_DATA_3 12
#define DATA_MEMORY_INPUT_MEMWRITE 13
#define DATA_MEMORY_INPUT_MEMREAD 14
#define DATA_MEMORY_INPUT_CLR 15
//Outputs
#define DATA_MEMORY_OUTPUT_0 16
#define DATA_MEMORY_OUTPUT_1 17
#define DATA_MEMORY_OUTPUT_2 18
#define DATA_MEMORY_OUTPUT_3 19


void setup() {
  //Data memory inputs
  pinMode(DATA_MEMORY_INPUT_ADDRESS_0, INPUT);
  pinMode(DATA_MEMORY_INPUT_ADDRESS_1, INPUT);
  pinMode(DATA_MEMORY_INPUT_ADDRESS_2, INPUT);
  pinMode(DATA_MEMORY_INPUT_ADDRESS_3, INPUT);
  pinMode(DATA_MEMORY_INPUT_ADDRESS_4, INPUT);
  pinMode(DATA_MEMORY_INPUT_ADDRESS_5, INPUT);
  pinMode(DATA_MEMORY_INPUT_ADDRESS_6, INPUT);
  pinMode(DATA_MEMORY_INPUT_ADDRESS_7, INPUT);
  pinMode(DATA_MEMORY_INPUT_WRITE_DATA_0, INPUT);
  pinMode(DATA_MEMORY_INPUT_WRITE_DATA_1, INPUT);
  pinMode(DATA_MEMORY_INPUT_WRITE_DATA_2, INPUT);
  pinMode(DATA_MEMORY_INPUT_WRITE_DATA_3, INPUT);
  pinMode(DATA_MEMORY_INPUT_MEMWRITE, INPUT);
  pinMode(DATA_MEMORY_INPUT_MEMREAD, INPUT);
  pinMode(DATA_MEMORY_INPUT_CLR, INPUT);
  //outputs
  pinMode(DATA_MEMORY_OUTPUT_0, OUTPUT);
  pinMode(DATA_MEMORY_OUTPUT_1, OUTPUT);
  pinMode(DATA_MEMORY_OUTPUT_2, OUTPUT);
  pinMode(DATA_MEMORY_OUTPUT_3, OUTPUT);

}

void loop() {
  // put your main code here, to run repeatedly:

}
